# Introducción a NumPy

### ¿Qué es NumPy?
NumPy (Numerical Python) es una librería fundamental para la computación científica en Python. Proporciona un objeto poderoso llamado array (arreglo), que es similar a una lista de Python, pero mucho más eficiente en términos de memoria y velocidad cuando se realizan cálculos matemáticos y científicos.

### Dónde encontrar documentación oficial:

http://www.numpy.org

### ¿Por qué usar NumPy?
- Velocidad: Los arrays de NumPy son más rápidos y ocupan menos espacio en comparación con las listas de Python.
- Operaciones vectorizadas: NumPy permite realizar operaciones matemáticas en vectores y matrices sin la necesidad de escribir bucles explícitos, lo que lo hace más eficiente.
- Funciones matemáticas avanzadas: Ofrece un conjunto amplio de funciones para álgebra lineal, transformadas de Fourier, estadísticas, etc.


In [38]:
# Nos importamos la librería y vemos qué vesión tenemos 
import numpy as np


Muchas personas utilizan la abreviatura de ``np`` como alias de Numpy:
```Python
        import numpy as np
```

In [39]:
import numpy as np

1. Creación de arreglos (arrays)
En NumPy, los arreglos son similares a las listas de Python, pero son más rápidos y consumen menos memoria.

`Nota: Un array, es un tipo de dato estructurado que permite almacenar un conjunto de datos homogeneo, es decir, todos ellos del mismo tipo y relacionados. `

Definimos tres matrices aleatorias, una matriz unidimensional, bidimensional y tridimensional.
Usaremos el generador de números aleatorios de NumPy, que *sembraremos* con un valor establecido para garantizar que se generen las mismas matrices aleatorias cada vez que se ejecuta este código:
- randon.seed = es una función en la biblioteca NumPy que establece la semilla para generar números aleatorios.
- randon.randint = devuelve números enteros aleatorios desde bajo (inclusive) hasta alto (exclusivo). 
    - Sintaxis: random.randint(low, high=None, size=None, dtype=int)

In [40]:
x1 = np.random.randint(10, size=6)  # array de una dimensión
x2 = np.random.randint(10, size=(3, 4))  # array de dos dimensiones
x3 = np.random.randint(10, size=(3, 4, 5))  # array de tres dimensiones

In [41]:
print('soy un arrauy de un dimension')
print(x1)
print('soy un arrauy de dos dimensiones')
print(x2)
print('soy un arrauy de tres dimensiones')
print(x3)

soy un arrauy de un dimension
[4 3 4 4 8 4]
soy un arrauy de dos dimensiones
[[3 7 5 5]
 [0 1 5 9]
 [3 0 5 0]]
soy un arrauy de tres dimensiones
[[[1 2 4 2 0]
  [3 2 0 7 5]
  [9 0 2 7 2]
  [9 2 3 3 2]]

 [[3 4 1 2 9]
  [1 4 6 8 2]
  [3 0 0 6 0]
  [6 3 3 8 8]]

 [[8 2 3 2 0]
  [8 8 3 8 2]
  [8 4 3 0 4]
  [3 6 9 8 0]]]


In [42]:
np.random.seed(0) #seed se utiliza si queremos dejar fija la semilla de números aleatorios que genermos

x1 = np.random.randint(10, size=6)  # array de una dimensión
x2 = np.random.randint(10, size=(3, 4))  # array de dos dimensiones
x3 = np.random.randint(10, size=(3, 4, 5))  # array de tres dimensiones

In [43]:
print(f"array de una sóla dimentsión {x1}")  # size=6

array de una sóla dimentsión [5 0 3 3 7 9]


In [44]:
print(f"array de dos dimentsiones {x2}") # size=(3, 4)

array de dos dimentsiones [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [45]:
print(f"array de tres dimentsiones {x3}") # size=(3, 4, 5)

array de tres dimentsiones [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


*    Crear un array de NumPy desde una lista:

In [46]:
# Crear un array unidimensional desde una lista y llo almaceno desde una variable
array = np.array([1, 2, 3, 4])
print(array)

[1 2 3 4]


In [47]:
# Realizar operaciones vectorizadas
print(array * 2)  # Multiplica cada elemento por 2

[2 4 6 8]


In [48]:
# array 2D (matriz)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


2. Propiedades de los array
Una vez que tienes un arreglo de NumPy, puedes obtener información sobre él, como su forma, tamaño y tipo de datos.

    - shape: devuelve una tupla con cada índice con el número de elementos correspondientes.
    - size: atributo que obtiene el número total de elementos, de una matriz NumPy.
    - dtype: devuelve el tipo de datos de la matriz.

In [49]:
print("Forma del arreglo:", arr_2d.shape)   # Dimensiones del arreglo , devuelve el tamaño de la lsita (2, 3) 

Forma del arreglo: (2, 3)


In [50]:
print("Tamaño del arreglo:", arr_2d.size)   # Número total de elementos


Tamaño del arreglo: 6


In [51]:
print("Tipo de datos:", arr_2d.dtype)       # Tipo de dato de los elementos

Tipo de datos: int64


3. Funciones de creación de arreglos
NumPy tiene varias funciones útiles para crear arreglos rápidamente:
    * np.zeros(): Crea un arreglo de ceros
    * np.ones(): Crea un arreglo de unos
    * np.arange(): Crea un arreglo con un rango de valores
    * np.linspace(): Genera números equiespaciados en un rango

Ejemplos:    


In [52]:
# np.zeros():

zeros_array = np.zeros((2, 3))  # Matriz 2x3 llena de ceros
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [53]:
# np.ones():

ones_array = np.ones((3, 2))    # Matriz 3x2 llena de unos
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [54]:
# np.arange():

range_array = np.arange(0, 10, 2)  # Números del 0 al 9, con paso de 2
print(range_array)

[0 2 4 6 8]


In [55]:
# np.linspace():

linspace_array = np.linspace(0, 1, 5)  # 5 valores entre 0 y 1, equidistantes
print(linspace_array)

[0.   0.25 0.5  0.75 1.  ]


4. Operaciones aritméticas con arreglos
NumPy permite realizar operaciones matemáticas en arreglos de forma rápida y eficiente.
    * Suma y resta
    * Multiplicación y división
    * Operaciones con escalares
    

In [56]:
# Temenos dos array
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [57]:
# Suma de array
suma = arr1 + arr2
print("Suma:", suma)

Suma: [5 7 9]


In [58]:
# Resta de array
resta = arr2 - arr1
print("Resta:", resta)

Resta: [3 3 3]


In [59]:
# Multiplicación elemento a elemento
multiplicacion = arr1 * arr2
print("Multiplicación:", multiplicacion)

Multiplicación: [ 4 10 18]


In [60]:
# División elemento a elemento
division = arr2 / arr1
print("División:", division)

División: [4.  2.5 2. ]


In [61]:
# Multiplicar todo el array por un escalar
escalar_mult = arr1 * 2
print("Multiplicado por 2:", escalar_mult)

Multiplicado por 2: [2 4 6]


5. Indexación y segmentación (slicing)
Puedes acceder a los elementos de un arreglo o extraer subarreglos usando índices, de manera similar a las listas de Python.
    * Acceso a elementos
    * Segmentación (slicing)
    * Indexación de arreglos 2D

5. 1 Acceso a los elementos
Así como podemos usar corchetes para acceder a elementos de matriz individuales, también podemos usarlos para acceder a submatrices con la notación *slice*, marcada por el carácter de dos puntos (``:``).
La sintaxis de corte de NumPy sigue la de la lista estándar de Python; para acceder a una porción de una matriz ``x``, use esto:
``` python
        x[inicio:parada:paso]
```
Si alguno de estos no está especificado, su valor predeterminado es ``start=0``, ``stop=``*``tamaño de dimensión``*, ``step=1``.
Veremos cómo acceder a submatrices en una dimensión y en múltiples dimensiones.

In [62]:
print(f"Acedemos al primer elemento {arr1[0]}")  # Primer elemento
print(f"Acedemos al último elemento {arr1[-1]}") # Último elemento

Acedemos al primer elemento 1
Acedemos al último elemento 3


In [63]:
arr = np.array([10, 20, 30, 40, 50])

# Extraer un subarray (del índice 1 al 3, sin incluir el 3)
sub_arr = arr[1:3]
print(sub_arr)

[20 30]


In [64]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Acceder a un elemento específico
print(f"Nuestro elemento específico es {arr_2d[1, 2]}")  # Elemento en la segunda fila, tercera columna (6)



Nuestro elemento específico es 6


In [65]:
# Acceder a una fila completa
print(f"Nuestra fila completa es {arr_2d[0, :]}")  # Primera fila completa



Nuestra fila completa es [1 2 3]


In [66]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
# Acceder a una columna completa
print(f"Nuestra columna completa es {arr_2d[:, 1]}")  # Segunda columna completa

Nuestra columna completa es [2 5 8]


6. Operaciones agregadas
NumPy incluye funciones para realizar operaciones agregadas en los array, como encontrar el valor máximo, mínimo o el promedio.

In [68]:
# Sumar los elementos de un array
print("Suma total:", np.sum(arr_2d))

Suma total: 45


In [69]:
# Encontrar el valor máximo y mínimo
print("Máximo:", np.max(arr_2d))
print("Mínimo:", np.min(arr_2d))

Máximo: 9
Mínimo: 1


In [70]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
# Calcular el promedio y la desviación estándar
print("Promedio:", np.mean(arr_2d))
print("Desviación estándar:", np.std(arr_2d))

Promedio: 5.0
Desviación estándar: 2.581988897471611


7. Manipulación de arreglos
Puedes cambiar la forma de un arreglo usando reshape, o combinar varios arreglos.

In [72]:
# Cambiar la forma de un array (reshape)
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape((2, 3))  # Cambiar a un array 2x3


In [73]:
arr

array([1, 2, 3, 4, 5, 6])

In [74]:
reshaped_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
print(f"Mi array original es {arr}")
print("-------------------------------------------------")
print(f"Mi array modificado es {reshaped_arr}")

Mi array original es [1 2 3 4 5 6]
-------------------------------------------------
Mi array modificado es [[1 2 3]
 [4 5 6]]


In [76]:
#Concatenar array
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenar dos array
concatenated = np.concatenate((arr1, arr2))
print(concatenated)

[1 2 3 4 5 6]


8. Funciones matemáticas
NumPy incluye muchas funciones matemáticas que puedes aplicar a los arreglos:

In [77]:
arr = np.array([1, 4, 9, 16])

# Raíz cuadrada de cada elemento
print(np.sqrt(arr))

[1. 2. 3. 4.]


In [78]:
# Exponencial (e^x) de cada elemento
print(np.exp(arr)) 

[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


In [79]:
# Trigonometría

angles = np.array([0, np.pi/2, np.pi])

    # Seno de los ángulos
print(f"el seno de angles es: {np.sin(angles)}")

    # Coseno de los ángulos
print(f"el coseno de angles es: {np.cos(angles)}")

el seno de angles es: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
el coseno de angles es: [ 1.000000e+00  6.123234e-17 -1.000000e+00]


---
### Vemos algunos Ejemplos de los metodos mas comunes de los Array:
---

## 1. Crear arrays

- `np.array([1, 2, 3])`: Convierte una lista en un array de numpy.
- `np.zeros((2, 3))`: Crea un array de ceros con forma \(2 \times 3\).
- `np.ones((3, 4))`: Crea un array de unos con forma \(3 \times 4\).
- `np.full((2, 2), 7)`: Crea un array \(2 \times 2\) lleno con el número 7.
- `np.eye(3)`: Crea una matriz identidad \(3 \times 3\).
- `np.arange(0, 10, 2)`: Crea un array de números desde 0 hasta 10, con un paso de 2.
- `np.linspace(0, 1, 5)`: Genera 5 números equidistantes entre 0 y 1.

In [80]:
import numpy as np

# 1. Crear arrays
array1 = np.array([1, 2, 3])
print(f"Array a partir de una lista de Python:\n{array1}")

array2 = np.zeros((2, 3))
print(f"Array de ceros con forma (2, 3):\n{array2}")

array3 = np.ones((3, 4))
print(f"Array de unos con forma (3, 4):\n{array3}")

array4 = np.full((2, 2), 7)
print(f"Array lleno con el valor 7 de forma (2, 2):\n{array4}")

identity = np.eye(3)
print(f"Matriz identidad de tamaño 3x3:\n{identity}")

arange_array = np.arange(0, 10, 2)
print(f"Array con rango de valores desde 0 hasta 10 (sin incluir) con paso 2:\n{arange_array}")

linspace_array = np.linspace(0, 1, 5)
print(f"Array con 5 valores equiespaciados entre 0 y 1:\n{linspace_array}")

Array a partir de una lista de Python:
[1 2 3]
Array de ceros con forma (2, 3):
[[0. 0. 0.]
 [0. 0. 0.]]
Array de unos con forma (3, 4):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array lleno con el valor 7 de forma (2, 2):
[[7 7]
 [7 7]]
Matriz identidad de tamaño 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Array con rango de valores desde 0 hasta 10 (sin incluir) con paso 2:
[0 2 4 6 8]
Array con 5 valores equiespaciados entre 0 y 1:
[0.   0.25 0.5  0.75 1.  ]


## 2. Propiedades del array

- `array.shape`: Obtiene la forma (dimensiones) del array.
- `array.size`: Devuelve el número total de elementos en el array.
- `array.ndim`: Muestra el número de dimensiones del array.
- `array.dtype`: Muestra el tipo de datos de los elementos del array.

In [81]:
shape = array3.shape
print(f"Forma del array (número de filas y columnas): {shape}")

size = array3.size
print(f"Número total de elementos en el array: {size}")

ndim = array3.ndim
print(f"Número de dimensiones del array: {ndim}")

dtype = array3.dtype
print(f"Tipo de dato de los elementos del array: {dtype}")

Forma del array (número de filas y columnas): (3, 4)
Número total de elementos en el array: 12
Número de dimensiones del array: 2
Tipo de dato de los elementos del array: float64



## 3. Operaciones matemáticas

- `np.add(array1, array2)`: Suma dos arrays elemento a elemento.
- `np.subtract(array1, array2)`: Resta dos arrays elemento a elemento.
- `np.multiply(array1, array2)`: Multiplica dos arrays elemento a elemento.
- `np.divide(array1, array2)`: Divide dos arrays elemento a elemento.
- `np.sqrt(array)`: Calcula la raíz cuadrada de cada elemento.
- `np.exp(array)`: Calcula el exponente de cada elemento.
- `np.log(array)`: Calcula el logaritmo natural de cada elemento.
- `np.abs(array)`: Calcula el valor absoluto de cada elemento.
- `np.power(array, n)`: Eleva cada elemento del array a la potencia \(n\).

In [82]:
print(f"Array 1 : \n{array1}")

sum_result = np.add(array1, [4, 5, 6])
print(f"Suma de array1 con [4, 5, 6]:\n {sum_result}")

subtract_result = np.subtract(array1, [1, 1, 1])
print(f"Resta de array1 menos [1, 1, 1]:\n{subtract_result}")

multiply_result = np.multiply(array1, [2, 2, 2])
print(f"Multiplicación elemento a elemento entre array1 y [2, 2, 2]:\n{multiply_result}")

divide_result = np.divide(array1, [1, 2, 3])
print(f"División elemento a elemento entre array1 y [1, 2, 3]:\n{divide_result}")

sqrt_result = np.sqrt(array1)
print(f"Raíz cuadrada de cada elemento en array1:\n{sqrt_result}")

exp_result = np.exp(array1)
print(f"Exponencial de cada elemento en array1:\n{exp_result}")

log_result = np.log(array1)
print(f"Logaritmo natural de cada elemento en array1:\n{log_result}")

abs_result = np.abs([-1, -2, -3])
print(f"Valor absoluto de la lista [-1, -2, -3]:\n{abs_result}")

power_result = np.power(array1, 2)
print(f"Potencia de cada elemento de array1 elevado al cuadrado:\n{power_result}")


Array 1 : 
[1 2 3]
Suma de array1 con [4, 5, 6]:
 [5 7 9]
Resta de array1 menos [1, 1, 1]:
[0 1 2]
Multiplicación elemento a elemento entre array1 y [2, 2, 2]:
[2 4 6]
División elemento a elemento entre array1 y [1, 2, 3]:
[1. 1. 1.]
Raíz cuadrada de cada elemento en array1:
[1.         1.41421356 1.73205081]
Exponencial de cada elemento en array1:
[ 2.71828183  7.3890561  20.08553692]
Logaritmo natural de cada elemento en array1:
[0.         0.69314718 1.09861229]
Valor absoluto de la lista [-1, -2, -3]:
[1 2 3]
Potencia de cada elemento de array1 elevado al cuadrado:
[1 4 9]


## 4. Estadísticas básicas

- `array.sum()`: Suma todos los elementos del array.
- `array.mean()`: Calcula la media de los elementos.
- `array.std()`: Calcula la desviación estándar.
- `array.var()`: Calcula la varianza.
- `array.min()`: Encuentra el valor mínimo.
- `array.max()`: Encuentra el valor máximo.
- `array.argmin()`: Índice del valor mínimo en el array.
- `array.argmax()`: Índice del valor máximo en el array.

In [83]:
print(f"Array 3 : \n{array3}")
sum_total = array3.sum()
print(f"Suma total de todos los elementos en array3:\n{sum_total}")

mean = array3.mean()
print(f"Media (promedio) de los elementos en array3:\n{mean}")

std_dev = array3.std()
print(f"Desviación estándar de los elementos en array3:\n{std_dev}")

variance = array3.var()
print(f"Varianza de los elementos en array3:\n{variance}")

min_value = array3.min()
print(f"Valor mínimo en array3:\n{min_value}")

max_value = array3.max()
print(f"Valor máximo en array3:\n{max_value}")

argmin_value = array3.argmin()
print(f"Índice del valor mínimo (en el array aplanado):\n{argmin_value}")

argmax_value = array3.argmax()
print(f"Índice del valor máximo (en el array aplanado):\n{argmax_value}")

Array 3 : 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Suma total de todos los elementos en array3:
12.0
Media (promedio) de los elementos en array3:
1.0
Desviación estándar de los elementos en array3:
0.0
Varianza de los elementos en array3:
0.0
Valor mínimo en array3:
1.0
Valor máximo en array3:
1.0
Índice del valor mínimo (en el array aplanado):
0
Índice del valor máximo (en el array aplanado):
0


## 5. Manipulación de arrays

- `array.reshape(new_shape)`: Cambia la forma del array sin cambiar sus datos.
- `array.flatten()`: Convierte un array multidimensional en un array de una sola dimensión.
- `array.transpose()`: Transpone el array (invierte filas y columnas).
- `np.concatenate((array1, array2), axis=0)`: Une dos arrays a lo largo de un eje especificado.
- `np.split(array, indices_or_sections)`: Divide un array en sub-arrays.
- `np.append(array, values)`: Añade elementos al final de un array.
- `np.insert(array, index, values)`: Inserta valores en un índice específico.
- `np.delete(array, index)`: Elimina un elemento del array en el índice dado.


In [84]:
print(f"Array 3 : \n{array3}")

reshaped_array = array3.reshape((4, 3))
print(f"Nuevo array con forma (4, 3) a partir de array3:\n{reshaped_array}")

flattened_array = array3.flatten()
print(f"Array aplanado (convertido en una sola dimensión):\n{flattened_array}")

transposed_array = array3.transpose()
print(f"Transpuesta del array3 (filas por columnas):\n{transposed_array}")

concatenated_array = np.concatenate((array3, np.zeros((3, 4))), axis=0)
print(f"Concatenación de array3 con otro array de unos de la misma forma:\n{concatenated_array}")

print(f"Array 3 : \n{array1}")
split_array = np.split(array1, 3)
print(f"División de array1 en 3 partes iguales:\n{split_array}")

appended_array = np.append(array1, [4, 5, 6])
print(f"Array después de añadir elementos [4, 5, 6] al final:\n{appended_array}")

inserted_array = np.insert(array1, 1, [7, 8])
print(f"Array después de insertar [7, 8] en la posición 1:\n{inserted_array}")

deleted_array = np.delete(array1, 1)
print(f"Array después de eliminar el elemento en la posición 1:\n{deleted_array}")


Array 3 : 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Nuevo array con forma (4, 3) a partir de array3:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array aplanado (convertido en una sola dimensión):
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Transpuesta del array3 (filas por columnas):
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Concatenación de array3 con otro array de unos de la misma forma:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array 3 : 
[1 2 3]
División de array1 en 3 partes iguales:
[array([1]), array([2]), array([3])]
Array después de añadir elementos [4, 5, 6] al final:
[1 2 3 4 5 6]
Array después de insertar [7, 8] en la posición 1:
[1 7 8 2 3]
Array después de eliminar el elemento en la posición 1:
[1 3]



## 6. Indexación y slicing

- `array[index]`: Accede al elemento en el índice especificado.
- `array[start:stop:step]`: Slice del array desde `start` hasta `stop`, con un `step`.
- `array[boolean_array]`: Filtra el array usando un array booleano.

In [85]:

indexed_element = array1[0]
print(f"Elemento en la posición 0 de array1:\n{indexed_element}")

sliced_array = arange_array[1:4]
print(f"Subarray desde la posición 1 hasta la 3 de arange_array:\n{sliced_array}")

filtered_array = array1[array1 > 1]
print(f"Elementos de array1 mayores a 1 (filtrado por condición):\n{filtered_array}")

Elemento en la posición 0 de array1:
1
Subarray desde la posición 1 hasta la 3 de arange_array:
[2 4 6]
Elementos de array1 mayores a 1 (filtrado por condición):
[2 3]


## 7. Operaciones de álgebra lineal

- `np.dot(array1, array2)`: Producto escalar entre dos arrays.
- `np.matmul(array1, array2)`: Multiplicación de matrices.
- `np.linalg.inv(matrix)`: Calcula la inversa de una matriz.
- `np.linalg.det(matrix)`: Calcula el determinante de una matriz.
- `np.linalg.eig(matrix)`: Calcula los valores y vectores propios de una matriz cuadrada.

In [86]:

dot_product = np.dot([2, 2], [3, 4])
print(f"Producto punto (dot product) entre [1, 2] y [3, 4]:\n{dot_product}")

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

matrix_mult = np.matmul(matrix1, matrix2)
print(f"Multiplicación de matrices (matrix1 x matrix2):\n{matrix_mult}")

matrix_inv = np.linalg.inv(matrix1)
print(f"Inversa de matrix1:\n{matrix_inv}")

matrix_det = np.linalg.det(matrix1)
print(f"Determinante de matrix1:\n{matrix_det}")

eigenvalues, eigenvectors = np.linalg.eig(matrix1)
print(f"Valores propios (eigenvalues) de matrix1:\n{eigenvalues}")
print(f"Vectores propios (eigenvectors) de matrix1:\n{eigenvectors}")

Producto punto (dot product) entre [1, 2] y [3, 4]:
14
Multiplicación de matrices (matrix1 x matrix2):
[[19 22]
 [43 50]]
Inversa de matrix1:
[[-2.   1. ]
 [ 1.5 -0.5]]
Determinante de matrix1:
-2.0000000000000004
Valores propios (eigenvalues) de matrix1:
[-0.37228132  5.37228132]
Vectores propios (eigenvectors) de matrix1:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]



## 8. Generación de números aleatorios

- `np.random.rand(d0, d1, ...)`: Genera un array de números aleatorios en un rango uniforme \([0,1)\) con la forma especificada.
- `np.random.randn(d0, d1, ...)`: Genera un array de números aleatorios de una distribución normal estándar.
- `np.random.randint(low, high, size)`: Genera números enteros aleatorios en un intervalo \([low, high)\).
- `np.random.choice(array, size)`: Selecciona elementos aleatoriamente de un array.

In [87]:

random_uniform = np.random.rand(3, 3)
print(f"Matriz 3x3 con valores aleatorios en distribución uniforme [0, 1):\n{random_uniform}")

random_normal = np.random.randn(2, 2)
print(f"Matriz 2x2 con valores aleatorios en distribución normal (media 0, varianza 1):\n{random_normal}")

random_integers = np.random.randint(1, 10, size=(2, 3))
print(f"Matriz 2x3 con enteros aleatorios entre 1 y 9 (incluido el 1, excluido el 10):\n{random_integers}")

random_choice = np.random.choice(array1, size=2)
print(f"Selección aleatoria de 2 elementos del array1:\n{random_choice}")


Matriz 3x3 con valores aleatorios en distribución uniforme [0, 1):
[[0.65279032 0.63505887 0.99529957]
 [0.58185033 0.41436859 0.4746975 ]
 [0.6235101  0.33800761 0.67475232]]
Matriz 2x2 con valores aleatorios en distribución normal (media 0, varianza 1):
[[ 1.0657892  -0.69993739]
 [ 0.14407911  0.3985421 ]]
Matriz 2x3 con enteros aleatorios entre 1 y 9 (incluido el 1, excluido el 10):
[[1 2 3]
 [5 3 1]]
Selección aleatoria de 2 elementos del array1:
[2 3]


---
### Ejercicios:
---

### Crea un array unidimensional 

In [88]:
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Crear un array bidimensional (matriz) de 3x3 con números enteros del 1 al 9.

In [89]:
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Creación de un array tridimensional, a partir de una lista de listas de listas.

In [90]:
lista3 = [[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]]
array3 = np.array(lista3)
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### Crea un Array de dos dimensiones de 4 filas por 4 columnas

In [91]:
zeros_array = np.zeros((4, 4))
zeros_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Crea un Array de numeros aleatorios de longitud  5

In [92]:
random_array = np.random.rand(5)
random_array

array([0.50962438, 0.05571469, 0.45115921, 0.01998767, 0.44171092])

### Crear un array que vaya de 0 a 10 y luego muestra los primeros 5 usando el metodo slicing

In [93]:
array= np.arange(11) 
array # Array de 0 a 10


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
primeros_cinco = array4[:5]
print(array)
print(primeros_cinco)

[ 0  1  2  3  4  5  6  7  8  9 10]
[[7 7]
 [7 7]]


### Dado un array de datos de ventas diarias en una tienda, 
### calcula la media, la mediana, el mínimo, el máximo y el desvío estándar.

ventas = np.array([120, 135, 150, 160, 125, 140, 130, 150, 155, 145])

In [95]:
ventas = np.array([120, 135, 150, 160, 125, 140, 130, 150, 155, 145])

media = np.mean(ventas)
mediana = np.median(ventas)
minimo = np.min(ventas)
maximo = np.max(ventas)
desviacion_estandar = np.std(ventas)
print(f'Media:{media}')
print(f'mediana:{mediana}')
print(f'minimo:{minimo}')
print(f'maximo:{maximo}')
print(f'desviacion_estandar:{desviacion_estandar}')

Media:141.0
mediana:142.5
minimo:120
maximo:160
desviacion_estandar:12.609520212918492


### Usa el array de ventas del ejercicio anterior y encuentra los días (índices) en los que las ventas fueron superiores al promedio.

In [96]:

días_superiores = np.where(ventas > media)
días_superiores

(array([2, 3, 7, 8, 9]),)

In [97]:
ventas_sup_media = ventas[ventas > media]
ventas_sup_media

array([150, 160, 150, 155, 145])

### Supón que tienes un array con los precios de cierre de una acción durante los últimos 15 días. 

Calcula el cambio diario (diferencia entre precios consecutivos) y el promedio de los cambios.

precios = np.array([150, 152, 148, 153, 155, 150, 147, 149, 151, 153, 155, 157, 156, 158, 159])

In [98]:
precios = np.array([150, 152, 148, 153, 155, 150, 147, 149, 151, 153, 155, 157, 156, 158, 159])
cambios_diarios = np.diff(precios)

cambios_diarios

array([ 2, -4,  5,  2, -5, -3,  2,  2,  2,  2,  2, -1,  2,  1])

In [99]:
promedio_cambios = np.mean(cambios_diarios)
promedio_cambios

np.float64(0.6428571428571429)